---
name: CatalystX-FacebookURI
version: 0.01
author:
  - 'Michael Nachbaur <mike@nachbaur.com>'
abstract: Automatically compose uri_for URIs to be within your Facebook application
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  CatalystX::FacebookURI:
    file: lib/CatalystX/FacebookURI.pm
    version: 0.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
